server:
  port: 8080
  servlet:
    context-path: /wu-web

spring:
  application:
    name: wu-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Orchard?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password
  thymeleaf:
    cache: false




#    suffix: .ftl


mybatis:
  type-aliases-package: com.wu.web.dao
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:/resources/mybatis/mapper/*.xml





